services:
  odoo17:
    image: odoo-dev:17
    container_name: odoo-dev-v17
    depends_on:
      - postgres16
    ports:
      - "8069:8069"
      - "8888:8888"
    volumes:
      - ./config:/etc/odoo
      - ./odoo-addons:/mnt/extra-addons
      - ./odoo:/usr/lib/python3/dist-packages/odoo # uncomment this if you want to mount odoo source code 
      - odoo-v17-data:/var/lib/odoo
    entrypoint: /usr/bin/python3 -m debugpy --listen 0.0.0.0:8888 /usr/bin/odoo -c /etc/odoo/odoo.conf
    # entrypoint: /usr/bin/python3 -m debugpy --listen 0.0.0.0:8888 /usr/bin/odoo -c /etc/odoo/odoo.conf -d odoo -i base
  
  postgres16:
    image: postgres:16
    container_name: postgres-v16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-v16-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-v17-data:
  postgres-v16-data:
